return {
  {
    "onsails/lspkind.nvim",
    lazy = true,
    enabled = vim.g.icons_enabled ~= false,
    opts = {
      mode = "symbol",
      symbol_map = {
        Array = "󰅪",
        Boolean = "⊨",
        Class = "󰌗",
        Color = "",
        Constant = "",
        Constructor = "",
        Enum = "",
        EnumMember = "",
        Event = "",
        Field = "󰽏",
        File = "",
        Folder = "󰉋",
        Function = "󰊕",
        Interface = "",
        Key = "󰌆",
        Keyword = "",
        Method = "",
        Module = "",
        Namespace = "",
        Null = "󰟢",
        Number = "",
        Object = "󰀚",
        Operator = "",
        Package = "",
        Property = "",
        Reference = "",
        Snippet = "",
        String = "󰀬",
        Struct = "",
        Text = "",
        TypeParameter = "",
        Unit = "",
        Value = "",
        Variable = "󰫧",
      },
      menu = {},
    },
  },
}
